[mongodb]
mongodb.nadalla.store

[catalogue]
catalogue.nadalla.store

[frontend]
frontend.nadalla.store

[redis]
redis.nadalla.store

[user]
user.nadalla.store

[cart]
cart.nadalla.store

[mysql]
mysql.nadalla.store

[shipping]
shipping.nadalla.store

[rabbitmq]
rabbitmq.nadalla.store

[payment]
payment.nadalla.store

[dispatch]
dispatch.nadalla.store

[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321
