---
 - name: configuring mongodb server
   become: true
   hosts: mongodb
   tasks:
   - name: copying mongo server
     ansible.builtin.copy:
       src: mongo.repo
       dest: /etc/yum.repos.d/mongo.repo

   - name: install mongodb server
     ansible.builtin.dnf: 
      name: mongodb-org 
      state: present


   - name: mongod start and enable 
     ansible.builtin.service:
       name: mongod
       state: started
       enabled: yes 

   - name: allow remote access
     ansible.builtin.replace:
      path: /etc/mongod.conf
      regexp: 127.0.0.1
      replace: 0.0.0.0

   - name: reloading server
     ansible.builtin.service:
       name: mongod
       state: restarted              